server:
  port: 8080

suncloud:
 #######异常相关配置项#########
  exception:
      ######默认错误信息 不配置则默认为 "服务器开小差了，请稍后再试。"##########
      default-error-info: 服务器开小差了，请稍后再试。
      ######默认错误状态 不配置默认为 400 #########
      default-status: 500
      ######扫描包路径,当 出现运行时异常时,提取此包下的堆栈信息,方便开发人员定位具体错误代码行###########
      base-package: cn
      ##### 默认错误页 ###
      error-html: 500

  ###### mybatis 参数配置 #####
  mybatis:
      plugin:
        pagehelper:
          properties:
            dialect: mysql
            reasonable: true
            supportMethodsArguments: false
            returnPageInfo: check
            params: count=countSql
spring:
  application:
    name: sun-cloud-deploy
  datasource:
    username: sunCloud
    password: sunCloud
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://47.98.204.145:3306/subspace?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    initial-size: 5
    max-active: 20
    max-idle: 8
    min-idle: 3
    max-wait: 500
    remove-abandoned: true
    remove-abandoned-timeout: 180
    test-while-idle: true
    ##验证
    validation-query: SELECT 1
    validation-query-timeout: 1
    time-between-eviction-runs-millis: 30000
    num-tests-per-eviction-run: 20
  redis:
    #Redis服务器地址
    host: 47.98.204.145
    #Redis服务器连接端口
    port: 6379
    # 连接池配置
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 20
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中的最小空闲连接
      min-idle: 0
    ##连接超时时间（毫秒）
    timeout: 0
    ##Redis数据库索引（默认为0）
    database: 0
    ##Redis服务器连接密码（默认为空）
    password:
#########全局配置项############
system:
  ###### 当异常出现时，使用json返回
  isAjax: true
  #######异常相关配置项#########
  exception:
    ######默认错误号############
    default-errorCode: 10000
    ######默认错误信息##########
    default-error-info: 系统罢工了,请等会再来
    ######默认错误状态#########
    default-status: 500
    ######扫描包路径,当 出现运行时异常时,提取此包下的堆栈信息,方便开发人员定位具体错误代码行###########
    basePackages: cn.winner
    ######异常错误号前缀配置,分为数据绑定,业务,系统 3类异常#######
    bind-exception-prefix: BIND-
    biz-exception-prefix: BIZ-
    system-exception-prefix: SYS-
  ####服务层参数验证相关配置##########
  validation:
    ####是否开启服务层参数验证,如果服务层单独部署需要开启次项########
    open-service-validation: true
  ######数据字典相关配置##########
  dictionary:
    ######当为找到字典项时是否抛出异常 默认false 表示不抛异常
    throw-exception-when-not-fund: false
    ######未找到时抛出的异常信息#######
    exception-message: "未找到字典项"
    ######未找的字典项时返回的默认信息#######
    not-fund-message: "未知"

#微信接口
weixin:
  #通过code获取用户的openid
  openid: wx4dda544bc4e0c910
  secret: 4fec7afdaf39a8e8ff29de1eecdeffcc
